### PR TITLE
Camera is ready

### LINKED ISSUE #51: Recieve camera frame from emulator
As a user I want to see images of the cars point of view from its environment so that I know where I am going.

Acceptance criteria: Camera feed is visible to user in the UI.

### LINKED ISSUE #52: Send camera frame to app from arduino sketch
As a user, I want to see where the car is in the UI so that I know where it is going.
Implement MQTT message to send over camera frames to UI. 
Acceptance criteria:
Using MQTT messages, camera frames are sent to UI.

### PR DESCRIPTION
**Pull request by Irina0904**
Camera has been added to both Android and Arduino side.

### CODE REVIEW

**Review by lucasnordic — COMMENTED** [review]
I don't think we need to remove line 91-93 and 96-97 in Client.

**Review by mandemmike — CHANGES_REQUESTED** [review]
Nice work, just change the final strings 'FAIL' and 'SUCCESS' so they say "Connection to TANK established" and not GeoBot, and as Lucas mentioned no need to take away the Ultrasonic sensor logging. Other than looks fine.

**Comment by Irina0904** [comment]
> Nice work, just change the final strings 'FAIL' and 'SUCCESS' so they say "Connection to TANK established" and not GeoBot, and as Lucas mentioned no need to take away the Ultrasonic sensor logging. Other than looks fine.

Thanks! I've changed the Client file.

**Review by lucasnordic — APPROVED** [review]
👍🏻 I think we can merge it

**Review by mandemmike — APPROVED** [review]
all good.

**Pull request merged**
