### PR TITLE
Improve Joystick performance

### LINKED ISSUE #47: Improved Movement (Joystick)
As a user I want good performance on the joystick so that the car can be operated more easily. 

Acceptance criteria: 
- [x] Movement of the car is smooth when using the joystick

### PR DESCRIPTION
**Pull request by Spidergirl93**
1. New directory added to the Arduino folder for the cars that are going to be crushed by Tank. 
2. The method of obstacle handling of these cars is the same as before.
3. Joystick performance is enhanced in this new version.
4. Obstacle handling in Tank is different from before. In the new version, Tank will lower the speed by 50% while approaching an obstacle giving time to the user to take some action.
5. Please test this and let me know what you think! 
#47 
#93

### CODE REVIEW

**Review by lucasnordic — COMMENTED** [review]
Looks good 👍🏻.  We have to increase the turn rate though. It's very hard to turn at the moment. 

As a bonus, it would be nice if we could get the car to turn while holding down left/right, but that might be too troublesome to figure out perhaps.

Another bonus, It's nice to have the serialReader, for debugging reasons. Maybe we could keep them at the bottom of the .ino?

**Comment by Spidergirl93** [comment]
> Looks good 👍🏻. We have to increase the turn rate though. It's very hard to turn at the moment.
> 
> As a bonus, it would be nice if we could get the car to turn while holding down left/right, but that might be too troublesome to figure out perhaps.
> 
> Another bonus, It's nice to have the serialReader, for debugging reasons. Maybe we could keep them at the bottom of the .ino?

1. The problem is apparently we can't hold a button in the android emulator. You have to keep clicking on the button to get a holding functionality. Have you tried this while turning? I know clicking over and over is a bit annoying but I am not sure if there is a way in android studio to hold a button. Tell me if I'm wrong.
 
2.  What exactly do you mean by serial reader? Do you mean reporting current states of the car(i.e. Speed, distance from other obstacles)?

**Comment by lucasnordic** [comment]
> > Looks good 👍🏻. We have to increase the turn rate though. It's very hard to turn at the moment.
> > As a bonus, it would be nice if we could get the car to turn while holding down left/right, but that might be too troublesome to figure out perhaps.
> > Another bonus, It's nice to have the serialReader, for debugging reasons. Maybe we could keep them at the bottom of the .ino?
> 
> 1. The problem is apparently we can't hold a button in the android emulator. You have to keep clicking on the button to get a holding functionality. Have you tried this while turning? I know clicking over and over is a bit annoying but I am not sure if there is a way in android studio to hold a button. Tell me if I'm wrong.
> 2. What exactly do you mean by serial reader? Do you mean reporting current states of the car(i.e. Speed, distance from other obstacles)?

The important thing is to be able to turn more rapidly, and that can simply be fixed in the .ino file right? Also, I think there must be some way in Android to hold a button, and then we can simply check for (as long as user holds down button, send MQTT turn message every 0.5 seconds). Or something like it.

The serial reader is in the .ino file. It outputs things to the SMCE console :)

**Comment by Spidergirl93** [comment]
> > > Looks good 👍🏻. We have to increase the turn rate though. It's very hard to turn at the moment.
> > > As a bonus, it would be nice if we could get the car to turn while holding down left/right, but that might be too troublesome to figure out perhaps.
> > > Another bonus, It's nice to have the serialReader, for debugging reasons. Maybe we could keep them at the bottom of the .ino?
> > 
> > 
> > 
> > 1. The problem is apparently we can't hold a button in the android emulator. You have to keep clicking on the button to get a holding functionality. Have you tried this while turning? I know clicking over and over is a bit annoying but I am not sure if there is a way in android studio to hold a button. Tell me if I'm wrong.
> > 2. What exactly do you mean by serial reader? Do you mean reporting current states of the car(i.e. Speed, distance from other obstacles)?
> 
> The important thing is to be able to turn more rapidly, and that can simply be fixed in the .ino file right? Also, I think there must be some way in Android to hold a button, and then we can simply check for (as long as user holds down button, send MQTT turn message every 0.5 seconds). Or something like it.
> 
> The serial reader is in the .ino file. It outputs things to the SMCE console :)

Done & Done! Check it out :)

**Comment by platisd** [comment]
> The problem is apparently we can't hold a button in the android emulator.

Is this really the case?

**Comment by Spidergirl93** [comment]
> > The problem is apparently we can't hold a button in the android emulator.
> 
> Is this really the case?

No, we used to have onClick for all the buttons and use delay function for turning and it made it very difficult to control the car. but now using onTouch, that problem is solved. It actually is possible to hold a button in android emulator. The problem was I didn't know how to do it and now I know!

**Comment by platisd** [comment]
Awesome! :tada:

**Review by lucasnordic — COMMENTED** [review]
It's nice that you got touch to work! Some thoughts:

- Instead of having duplicated code for each button we can make a method "setButtonTouch", that takes in a single button as an argument. Then, in setJoystickBtns we only need to have four lines of code: setButtonTouch(forwardBtn).
- If I hold down left or right for more than 3 seconds the car can get into a loop. If I hold it in for longer, the car will simply keep on turning around the same spot. It's not easy to hunt with Tank when this happens. I see some code, "removeCallbacks"? I have to look into it but maybe this line of code is supposed to deal with this?
- It was nice to be able to accelerate up/down before, but the added "speed at 100% only", definitely helps Tank reach its targets faster. 🤔 It's not as easy to mis-press now and accidentally hit accelerate buttons. And larger joystick buttons are always nice 💪🏻

**Comment by Spidergirl93** [comment]
> It's nice that you got touch to work! Some thoughts:
> 
> * Instead of having duplicated code for each button we can make a method "setButtonTouch", that takes in a single button as an argument. Then, in setJoystickBtns we only need to have four lines of code: setButtonTouch(forwardBtn).
> * If I hold down left or right for more than 3 seconds the car can get into a loop. If I hold it in for longer, the car will simply keep on turning around the same spot. It's not easy to hunt with Tank when this happens. I see some code, "removeCallbacks"? I have to look into it but maybe this line of code is supposed to deal with this?
> * It was nice to be able to accelerate up/down before, but the added "speed at 100% only", definitely helps Tank reach its targets faster. 🤔 It's not as easy to mis-press now and accidentally hit accelerate buttons. And larger joystick buttons are always nice 💪🏻

Interesting. the loop thingy doesn't happen for me, I tried it a few times. I will look into it more. About the first part, actually I also wanted to create a method to reduce that bulk of code in that area but the structure of that part is a bit unfamiliar and difficult and I couldn't figure it out . So feel free to improve it  if you are interested. And about the last part, Thank you!

**Review by lucasnordic — APPROVED** [review]
Ok, looks good. I think we can merge it.

Maybe create a new issue to fix the resize issue of the joystick, since that seems like a hard problem to fix 🤔 . Otherwise Good job!

**Comment by Spidergirl93** [comment]
> Ok, looks good. I think we can merge it.
> 
> Maybe create a new issue to fix the resize issue of the joystick, since that seems like a hard problem to fix 🤔 . Otherwise Good job!

yeay

**Pull request merged**
