### PR TITLE
Sound effects complementation

### LINKED ISSUE #103: Win/lose sound effects
As a gamer, I want to hear music when I win or lose so that I know how to react.

Acceptance criteria:
- [x] Sound effects are played when win or lose dialog displays

### PR DESCRIPTION
**Pull request by Spidergirl93**
New sound effects are added to win/lose windows. Now different sounds will be played if the user wins or loses the game.

Resolves #103

### CODE REVIEW

**Comment by hannahshiels** [comment]
The only issue I can see is that the music continues after the activity is reloaded from the dialog. But I don't really think this is a big issue, so maybe we could keep it like this?

**Comment by Spidergirl93** [comment]
I'll try to fix it.

**Comment by Irina0904** [comment]
> The only issue I can see is that the music continues after the activity is reloaded from the dialog. But I don't really think this is a big issue, so maybe we could keep it like this?

I think for me the music only continued for a couple of seconds and then stopped, so I would say it's fine. The car is much more responsive now and I really like the music after the win/lose screens. Keep it up!

**Comment by lucasnordic** [comment]
Maybe we can add some gameplay music too? :⭕ Good choice of win/lose music!

**Comment by Spidergirl93** [comment]
Now the win/lose music will be played fully in the pop up window. and they will stop if the user chooses one of the options. I will add a good background music if I find any. Have any suggestions?

**Review by Irina0904 — APPROVED** [review]

**Comment by lucasnordic** [comment]
> Now the win/lose music will be played fully in the pop up window. and they will stop if the user chooses one of the options. I will add a good background music if I find any. Have any suggestions?

- My favourite: https://www.bensound.com/royalty-free-music/track/good-mood-funny-catchy
- https://www.bensound.com/royalty-free-music/track/kickshot-modern-action-rock
- https://www.bensound.com/royalty-free-music/track/high-octane-heavy-hard-rock-metal
- More funky: https://www.bensound.com/royalty-free-music/track/in-trend-funky-comedy
- Fun: https://www.bensound.com/royalty-free-music/track/fabulous-gypsy-jazz-kids-fun

**Comment by Spidergirl93** [comment]
> > Now the win/lose music will be played fully in the pop up window. and they will stop if the user chooses one of the options. I will add a good background music if I find any. Have any suggestions?
> 
> * My favourite: https://www.bensound.com/royalty-free-music/track/good-mood-funny-catchy
> * https://www.bensound.com/royalty-free-music/track/kickshot-modern-action-rock
> * https://www.bensound.com/royalty-free-music/track/high-octane-heavy-hard-rock-metal
> * More funky: https://www.bensound.com/royalty-free-music/track/in-trend-funky-comedy
> * Fun: https://www.bensound.com/royalty-free-music/track/fabulous-gypsy-jazz-kids-fun

All of these are great thanks! But unfortunately only one of the links has free license and it's not your favorite one (srry :)). But I think it suits our game so this branch will be merged to master after having a background game music. YEAY!

**Comment by Spidergirl93** [comment]
The background music is added. It starts after the timer starts ticking. Check it out and tell me if you have sth on mind

**Comment by hannahshiels** [comment]
> 
> 
> The background music is added. It starts after the timer starts ticking. Check it out and tell me if you have sth on mind

On my computer, the music doesn't stop if you go back to the main screen which kind of messes with the video and sound there. Double check on yours though, otherwise we are good to merge 👍

**Comment by Spidergirl93** [comment]
Thanks for mentioning the bug. It's successfully handled. And the volume of the music is increased a bit higher.

**Pull request merged**
