### PR TITLE
adding timer feature

### LINKED ISSUE #79: Timer
As a user I want to know how much time I have to get a number of scores, so that I have a chance to win the game.

Acceptance criteria:

- [x] The game stops after a certain amount of time 
- [x] The user is notified about how much time is left

### PR DESCRIPTION
**Pull request by himankmeattle**
Added timer to the UI. After user hit the play button and move the joystick, timer will kick off. The timer duration is kept for 2min/120sec now. The timer is shown below the joystick for now. The timer starts from 120 and decrements. Once the time is up, it will display time up. Based on score >1, win dialog will be displayed otherwise lose dialog.

### CODE REVIEW

**Comment by himankmeattle** [comment]
Please review again.

**Comment by Spidergirl93** [comment]
- The timer feature is nicely done. The pop up window is pretty and user-friendly. However in the description it is mentioned that the timer will stop after 3 minutes, but now the window will appear less than a minute maybe. And The timer doesn't show it to the user that how much time is left. It just shows 0 when time's up (Or maybe it is showing the time but the font color is the same as the background and The user can't see it?). I think it would be nicer if it shows the remaining time and counts down.

- Another issue is when restarting the game from the pop up window, the scores are the same as the last game and they don't start from 0. I'm not sure if this is related to this branch or not. Let us know if we need to have another issue for fixing this.

**Comment by himankmeattle** [comment]
@Spidergirl93 , thanks for the feedback. Yes it set to 1 min/60 sec and i have updated the description here as well. For now we say 60 sec and score >= 2 should make a win otherwise lose and we shall discuss in the meeting today what is the ideal values we shall use. the other issue is not related to this feature but i can fix and will do.

**Comment by hannahshiels** [comment]
I think you can get rid of the && counter <= 15000 part of the if statement in showDialog(). As far as I know, it doesn't have anything to do with winning or losing logic, and the dialog is being displayed when the timer is finished anyway.

**Review by lucasnordic — APPROVED** [review]
Maryam, your thoughts are addressed. The timer decreases from 2 minutes to 0 now.

And Hannah, we can discuss the counter in a meeting, otherwise It all seems good to me 👍🏻

**Comment by himankmeattle** [comment]
@hannahshiels , @lucasnordic , I have removed the and condition from if statement.

**Pull request merged**
