### PR TITLE
Game sound effects

### LINKED ISSUE #86: Add sound effects to the Tank controllers
As a gamer, I want to hear music when I move the joystick and play the game so that I have fun playing the game.

Acceptance criteria:
- [x] Add sound effect to the buttons and joystick
- [x] Add a proper ear-friendly music to the background of game

### PR DESCRIPTION
**Pull request by Spidergirl93**
The features implemented in this branch are as follow:

- [ ] Joystick and break button has their own sound effect now. 
- [ ] Break button's method is changed from OnListener to OnTouch to have a better sound effect on it.

Enjoy controlling Tank with sound! The current sound effects are preliminary and can be replaced with better ones later if everyone agrees.

### CODE REVIEW

**Comment by lucasnordic** [comment]
I think it's great. It would be nicer if the audio "smothed out" when dropping the joystick though, instead of completely stopping.

**Comment by Irina0904** [comment]
> I think it's great. It would be nicer if the audio "smothed out" when dropping the joystick though, instead of completely stopping.

I agree with Lucas. Could we make the sound more quiet when we drop the joystick? When we drop the joystick, the car still continues to move so our "engine" is kind of still working. Maybe the sound can be turned off completely when we hit "brake"? Otherwise it's a great idea!

**Comment by Spidergirl93** [comment]
> I think it's great. It would be nicer if the audio "smothed out" when dropping the joystick though, instead of completely stopping.
> I agree with Lucas. Could we make the sound more quiet when we drop the joystick? When we drop the joystick, the car still continues to move so our "engine" is kind of still working. Maybe the sound can be turned off completely when we hit "brake"? Otherwise it's a great idea!


Yeah that's a great Idea. I'm gonna start implementing that after the final joystick is ready since they are dependent of each other.

**Comment by Spidergirl93** [comment]
I just add this in another pull req since there is too much difference between this branch and master and I don't want to spend time on resolving all of them

**Pull request closed without merging**
