### PR TITLE
Main-screen is updated with video and sound

### PR DESCRIPTION
**Pull request by lucasnordic**
* A video and necessary classes for loading the video were added.
* Background music was added
* It is now possible to get help from the main menu
* The Apps Main Screen now displays the appropriate amount of evilness for Tank

Solves 3 of the mentioned points in #76 

image

### CODE REVIEW

**Review by hannahshiels — COMMENTED** [review]
As far as I can tell, everything is working as intended. One suggestion though, wouldn't the help circle button be better on the right side of the word tank? I think it would look better and be more readable :) Great job guys 😀

**Comment by lucasnordic** [comment]
> As far as I can tell, everything is working as intended. One suggestion though, wouldn't the help circle button be better on the right side of the word tank? I think it would look better and be more readable :) Great job guys 😀

I agree with you on that. And thanks :)

**Comment by lucasnordic** [comment]
Changed the icon to the right of the text and made it the same size as the lowercase letters 
image

**Comment by hannahshiels** [comment]
Looks much better!

**Review by hannahshiels — APPROVED** [review]

**Pull request merged**
